import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "../navbar";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Copywriting.work",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col h-screen">
      <div><Navbar /></div>
      <nav className="mx-2 md:mx-5 my-1">
        <ul className="flex flex-row text-xs md:text-sm font-semibold gap-1 md:gap-3 flex-wrap">
          <li>
            <Link href="/" className="block px-2 md:px-4 py-1 md:py-2 rounded hover:bg-violet-500 hover:text-white transition-colors">Assignment</Link>
          </li>
          <li>
            <Link href="/rental" className="block px-2 md:px-4 py-1 md:py-2 rounded hover:bg-violet-500 hover:text-white transition-colors">Rental</Link>
          </li>
          <li>
            <Link href="/notes" className="block px-2 md:px-4 py-1 md:py-2 rounded hover:bg-violet-500 hover:text-white transition-colors">Notes</Link>
          </li>
          <li>
            <Link href="/canteen" className="block px-2 md:px-4 py-1 md:py-2 rounded hover:bg-violet-500 hover:text-white transition-colors">Canteen</Link>
          </li>
        </ul>
      </nav>
      <div className="p-2">
        <div className="w-full bg-linear-to-r from-violet-400 to-violet-600 h-1 "></div>
      </div>
      <main className="flex-1 min-h-0">
        {children}
      </main>
    </div>
  );
}
