import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "../navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div><Navbar></Navbar></div>
        <nav className="mx-5 my-1">
          <ul className="flex flex-row text-sm font-semibold gap-3">
            <li>
              <a href="/" className="block px-4 py-2 rounded hover:bg-orange-500 hover:text-white transition-colors">Assignment</a>
            </li>
            <li>
              <a href="rental" className="block px-4 py-2 rounded hover:bg-orange-500 hover:text-white transition-colors">Rental</a>
            </li>
            <li>
              <a href="notes" className="block px-4 py-2 rounded hover:bg-orange-500 hover:text-white transition-colors">Notes</a>
            </li>
            <li>
              <a href="canteen" className="block px-4 py-2 rounded hover:bg-orange-500 hover:text-white transition-colors">Canteen</a>
            </li>
          </ul>
        </nav>
        <div className="p-2">
        <div className="w-full bg-gradient-to-r from-orange-400 to-orange-600 h-1 "></div>
        </div>
        {children}
      </body>
    </html>
  );
}
